# Generated by Django 4.1.7 on 2023-03-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='past_period',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
