# Generated by Django 4.1.7 on 2023-03-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0002_alter_subscription_past_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
