# Generated by Django 4.1.7 on 2023-03-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0003_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
