# Generated by Django 4.1.7 on 2023-03-17 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0005_remove_subscription_owner_store_owner_delete_crowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='owner',
        ),
    ]
