# Generated by Django 4.1.7 on 2023-03-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0006_remove_store_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='remaining_period',
        ),
        migrations.AddField(
            model_name='subscription',
            name='extension',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='remaining',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='past_period',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='period',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
