# Generated by Django 4.1.7 on 2023-03-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0007_remove_subscription_remaining_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='store',
        ),
    ]
