# Generated by Django 4.1.7 on 2023-03-17 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0008_remove_subscription_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='store',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='subs.store'),
            preserve_default=False,
        ),
    ]
