# Generated by Django 4.1.7 on 2023-03-18 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('subs', '0009_subscription_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
