# Generated by Django 4.1.7 on 2023-03-18 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0010_alter_subscription_store_delete_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subs.store'),
        ),
    ]
