# Generated by Django 4.1.7 on 2023-03-18 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0011_store_alter_subscription_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='past_period',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='remaining',
        ),
    ]
