# Generated by Django 4.1.7 on 2023-03-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0012_remove_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='extension',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
