# Generated by Django 4.1.7 on 2023-03-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0014_remove_subscription_extension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='period',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
