# Generated by Django 4.1.7 on 2023-03-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='inventory',
        ),
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(default='-'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='-'),
        ),
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.SlugField(default='-'),
        ),
    ]
